### ISSUE TITLE
Bell sound alert when giving me the prompt "(y/n)?"

### ISSUE THREAD

**Issue by ghost** [sakaki-/genup#1]
I have feature request: when running script with flag `--ask` add bell sound alert every time the interaction is needed (for example: when appears question `Continue (y/n)?`). It would be very convenient.

I found that's very easy to implement:
http://rosettacode.org/wiki/Terminal_control/Ringing_the_terminal_bell#UNIX_Shell

**Comment by sakaki-** [comment]
Hi, OK I will look at adding this as an option. Making the noise is easy enough (`tput bel`), as is outputting this anytime `genup` (or `buildkernel`) itself prompts. Also `emerge` has a `--alert` option which could be passed through to make it vocalize.

I guess that would probably cover most of what you want (monitoring an interactive shell to detect certain strings is not trivial, so I'd rather avoid that route if possible)?

Best, sakaki

**Comment by ghost** [comment]
Yes.

Thank you very much.

**Comment by sakaki-** [comment]
Hi, just released `genup-1.0.8` (and `buildkernel 1.0.12`) with the feature you requested. To try it, first update `sakaki-tools` (running your existing version of `genup` should achieve this), then call `genup` with the `--alert` (or `-A`) flag to get the interactive prompt bell (this will automatically turn on `--ask` for you also).

Please let me know if this works at your end (and close out this issue if so).

Best, sakaki

**Comment by ghost** [comment]
It works perfectly.
