### ISSUE TITLE
genup doesn't seem to emerge --sync the main gentoo repo

### ISSUE THREAD

**Issue by pmundkur** [sakaki-/genup#11]
genup was working fine until a few months ago.

Now I keep seeing messages like in genup's log:
 * Last emerge --sync was 144d 17h 31m 48s ago.

genup -v -n gives:
[genup.log](https://github.com/sakaki-/genup/files/4429147/genup.log)

**Comment by sakaki-** [comment]
Strange. What do you have in `/etc/portage/repos.conf/gentoo.conf`?

**Comment by pmundkur** [comment]
$ cat /etc/portage/repos.conf/gentoo.conf

[DEFAULT]
main-repo = gentoo

[gentoo]
location = /usr/portage
sync-type = rsync
auto-sync = no
sync-uri = rsync://rsync.us.gentoo.org/gentoo-portage

**Comment by sakaki-** [comment]
Try changing `auto-sync` to `yes` and running (as root, or via `sudo`) `emaint sync --repo gentoo`.
Does that successfully update your tree?
PS `/usr/portage` has migrated to `/var/db/repos/gentoo`, but as far as I know using the old paths shouldn't break anything.

**Comment by pmundkur** [comment]
Changing `auto-sync` to `yes` and running emaint sync indeed updated
the tree.  genup also works now!  Thanks!
