### ISSUE TITLE
Add other package updaters/modularize

### ISSUE THREAD

**Issue by ngerstle** [sakaki-/genup#4]
Currently, `genup` syncs and updates the portage tree, overlays, and packages, rebuilds modules, and then explicitly updates perl and python modules using `perl-cleaner` and `python-updater`.
Other languages/environments maintain their own updaters- `haskell-updater` is the one giving rise to this issue.
I'll see if I can get around to throwing together a pull request for adding a call to `haskell-updater` in the script, but is that the correct approach to take? 
Can/should the addition of other package management tools be incorporated in a more coherent fashion?

**Comment by sakaki-** [comment]
Hi, thanks for the feedback.

If `genup` were to be extended to call various updaters directly (for languages not in the baseline @system set, such as haskell) then maintaining the package dependency and associated USE flags could quickly become an issue...

An alternative approach might be to support something like an `/etc/genup/updaters.d` directory - and then have `genup` (at the appropriate point) run all files (flagged as executable) found therein, failing if any do not return a 0 exit status. There could be also be a command line option to suppress `genup` checking this directory at all.

Would something like that suffice for your use case? If so, I can look at adding it. Best, sakaki

**Comment by sakaki-** [comment]
Hi, I've just released `genup-1.0.11`, which adds an `/etc/genup/updaters.d` directory. `genup` will run all executable files (or symlinks to executable files) found at the top level in that directory, at the end of its run (unless the `--no-custom-updaters` option is passed), and will immediately exit with an error should any of them return a non-zero exit status. The ebuild includes some examples, in `/etc/genup/updaters.d/examples`; copy or link these into the `/etc/genup/updaters.d` directory to have them run. The file `/etc/genup/updaters.d/examples/22-haskell-updater.sh` should hopefully address your use case if copied up.

I'm very open to pull requests for more sophisticated handlers to place in the `examples` directory; please address any of those to the [genup](https://github.com/sakaki-/sakaki-tools/tree/master/app-portage/genup) package within `sakaki-tools`. Thanks!

**Comment by ngerstle** [comment]
Looks great to me- thanks for the update!

**Comment by sakaki-** [comment]
Assuming this is working OK now so closing - please re-open if you experience problems.
Best, sakaki
